// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrlimjtjppsgbcseilzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybGltanRqcHBzZ2Jjc2VpbHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTExMTUsImV4cCI6MjA3MTU2NzExNX0.wr_MJ3rMhHMCbiDoeL2gzlhYpYogqntEQWfWaLln7Yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});